name: softcentotp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pin_code_fields: ^7.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
  uses-material-design: true

